### ISSUE TITLE
1000px以下の端末で、1000px幅ウィンドウと同じ比率に縮小表示できない

### ISSUE THREAD

**Issue by test20210616** [dsktschy/viewport-extra#17]
### 1.metaタグ

examples/no-framework/index.html
の
`<meta name="viewport-extra" content="width=device-width,initial-scale=1,min-width=414"/>`
の「`min-width=414`」を「`min-width=1000`」にします。

### 2.css

examples/no-framework/styles/globals.css
の「`.page`」セレクタの「`width: 414px;`」を「`width: 1000px;`」にします。
「`.page`」セレクタの「`height: 100vh;`」を消します。

### 3.bodyタグ内

下記に差し替えます。

```
<div class="page">
        <p>----------------------------------------------------- 1000px wide text --------------------------------------------------</p>
        <p>----------------------------------------------------- 1000px wide text --------------------------------------------------</p>
    </div>
```
### 4.結果

PCでは「1000px wide text 」が一行に収まっているのに対し、スマホで表示すると
HTMLの「1000px wide text 」が改行されて大幅に折り返されて表示されてしまいます。
pタグを1つにしたり、「`height: 100vh;`」を復活すると直ります。
PC=mac safari バージョン17.3
スマホ＝iPhone safari (OS16.7.5)

**Comment by dsktschy** [comment]
@test20210616
ご報告ありがとうございます。

global.cssに下記を追加することで解消するかと思います。
```css
body {
  -webkit-text-size-adjust: 100%;
}
```

examplesとREADME.mdに追記し、このスタイル付与の自動化も検討します。

**Comment by test20210616** [comment]
回答いただいた方法で解消いたしました。本当にありがとうございました。

**Comment by dsktschy** [comment]
`examples/*`と`README.md`への追記を完了しました。
また、`text-size-adjust`の自動付与機能も検討しておりましたが、`meta[name="viewport"]`要素の拡張という目的からは外れるため、見送りました。
あらためて、ご報告ありがとうございました。
