### ISSUE TITLE
initialScale  Accuracy problem

### ISSUE THREAD

**Issue by fengwuxp** [dsktschy/viewport-extra#7]
You only need to keep one decimal place. Too high precision may lead to browser calculation errors
![image](https://user-images.githubusercontent.com/19926995/149775597-96fc6feb-722a-4385-b0c8-0e485d0b6175.png)

example
`
parseFloat((documentClientWidth / minWidth) * initialScale).toFixed(1)
`

**Comment by dsktschy** [comment]
@fengwuxp
What's wrong with this image?
Please tell me more about the error.

- Expected behavior
- Actual behavior
- To Reproduce
- Your environment
  - Device
  - OS
  - Browser
  - Version of Viewport Extra

Thank you.
